# Use postgres/example user/password credentials
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products_db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - 8085:8080
