# Utilisation des identifiants par défaut pour PostgreSQL et Adminer
services:
  postgres:
    image: postgres
    container_name: postgres
    restart: always
    ports:
      - '5434:5432'
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: products_db

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - '8085:8080'

  product-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: product-container
    restart: always
    ports:
      - '8081:8082'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/products_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres
